# Understanding TensorFlow

Importing TensorFlow

In [1]:
import tensorflow as tf

C:\Users\Prajakta Pardeshi\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
a = tf.constant([2])
b = tf.constant([3])

After that, let's make an operation over these variables. The function tf.add() adds two elements (you could also use c = a + b). 

In [3]:
c = tf.add(a,b)

TensorFlow needs to initialize a session to run our code

In [4]:
session = tf.Session()

In [6]:
result = session.run(c)
print(result)

[5]


Close the session to release resources:

In [9]:
session.close()

To avoid having to close sessions every time, we can define them in a with block, so after running the with block the session will close automatically

In [10]:
with tf.Session() as session:
    result = session.run(c)
    print(result)

[5]


Data structures in TensorFlow

Summarizing:<br><br>
<table style="width:100%">
  <tr>
    <td><b>Dimension</b></td>
    <td><b>Physical Representation</b></td> 
    <td><b>Mathematical Object</b></td>
    <td><b>In Code</b></td>
  </tr>
  
  <tr>
    <td>Zero </td>
    <td>Point</td> 
    <td>Scalar (Single Number)</td>
    <td>[ 1 ]</td>
  </tr>

  <tr>
    <td>One</td>
    <td>Line</td> 
    <td>Vector (Series of Numbers) </td>
    <td>[ 1,2,3,4,... ]</td>
  </tr>
  
   <tr>
    <td>Two</td>
    <td>Surface</td> 
    <td>Matrix (Table of Numbers)</td>
    <td>[ [1,2,3,4,...], [1,2,3,4,...], [1,2,3,4,...],... ]</td>
  </tr>
  
   <tr>
    <td>Three</td>
    <td>Volume</td> 
    <td>Tensor (Cube of Numbers)</td>
    <td>[ [[1,2,...], [1,2,...], [1,2,...],...], [[1,2,...], [1,2,...], [1,2,...],...], [[1,2,...], [1,2,...], [1,2,...] ,...]... ]</td>
  </tr>
  
</table>

Defining multidimensional arrays using TensorFlow

In [16]:
# Represents a point
Scalar = tf.constant([2])

# Represents a vector
Vector = tf.constant([5,6,2])

# Represents a matrix
Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])

# Represents a tensor
Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )

with tf.Session() as session:
    result = session.run(Scalar)
    print ("Scalar (1 entry):\n %s \n" % result)
    
    result = session.run(Vector)
    print ("Vector:\n %s \n" % result)
    
    result = session.run(Matrix)
    print("Matrix:\n %s \n" % result)
    
    result = session.run(Tensor)
    print("Tensor:\n %s \n" % result)

Scalar (1 entry):
 [2] 

Vector:
 [5 6 2] 

Matrix:
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor:
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



Matrix operations using tensorflow

In [17]:
Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

first_operation = tf.add(Matrix_one, Matrix_two)
second_operation = Matrix_one + Matrix_two

with tf.Session() as session:
    result = session.run(first_operation)
    print ("Defined using tensorflow function :")
    print(result)
    result = session.run(second_operation)
    print ("Defined using normal expressions :")
    print(result)

Defined using tensorflow function :
[[3 4 5]
 [4 5 6]
 [5 6 7]]
Defined using normal expressions :
[[3 4 5]
 [4 5 6]
 [5 6 7]]


-----------------------------

Matrix Multiplication

In [18]:
Matrix_one = tf.constant([[2,3],[3,4]])
Matrix_two = tf.constant([[2,3],[3,4]])

first_operation = tf.matmul(Matrix_one, Matrix_two)

with tf.Session() as session:
    result = session.run(first_operation)
    print ("Defined using tensorflow function :")
    print(result)

Defined using tensorflow function :
[[13 18]
 [18 25]]


---------------------------------------------------------------------------

Variables

In [19]:
state = tf.Variable(0)

In [20]:
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

Variables must be initialized by running an initialization operation after having launched the graph. We first have to add the initialization operation to the graph:

In [21]:
init_op = tf.global_variables_initializer()

In [22]:
with tf.Session() as session:
  session.run(init_op)
  print(session.run(state))
  for _ in range(3):
    session.run(update)
    print(session.run(state))

0
1
2
3


Placeholders

create a placeholder

In [25]:
a = tf.placeholder(tf.float32)

And define a simple multiplication operation

In [27]:
b = a*2

To pass the data to the model we call the session with an extra argument feed_dict in which we should pass a dictionary with each placeholder name folowed by its respective data

In [28]:
with tf.Session() as sess:
    result = sess.run(b,feed_dict={a:3.5})
    print (result)

7.0


Another form of dictionary passed as data

In [29]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print (result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


Operations

In [31]:
a = tf.constant([5])
b = tf.constant([2])
c = tf.add(a,b)
d = tf.subtract(a,b)

with tf.Session() as session:
    result = session.run(c)
    print ('c =: %s' % result)
    result = session.run(d)
    print ('d =: %s' % result)

c =: [7]
d =: [3]
